name: Build Rmarkdown container (env/qc_markdown.Dockerfile)

on:
  push:
    paths:
    - 'env/qc_markdown.Dockerfile'
    - '.github/workflows/qc_markdown.yml'
  pull_request:
    paths:
    - 'env/qc_markdown.Dockerfile'
    - '.github/workflows/qc_markdown.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Build Tools
    - name: Build and Publish
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: sjwidmay/haplotype_reconstruction_qtl_nf
        username: ${{ secrets.SJW_DOCKER_USER }}
        password: ${{ secrets.SJW_DOCKER_PASS }}
        snapshot: true
        dockerfile: qc_markdown.Dockerfile
        workdir: "env"
        tags: "qc_markdown"
